### ISSUE TITLE
Running on Jenkins Linux "Execute Shell Script"

### ISSUE THREAD

**Issue by JonathonCwik** [michaelsogos/pg-diff#26]
Getting this error when running "Execute Shell" command with pg-diff:

TypeError: process.stdout.clearLine is not a function
    at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.16.1/lib/node_modules/pg-diff-cli/main.js:74:21)
    at EventEmitter.emit (events.js:200:13)
    at Function.compare (/home/ubuntu/.nvm/versions/node/v12.16.1/lib/node_modules/pg-diff-cli/node_modules/pg-diff-api/src/api/CompareApi.js:19:16)
    at PgDiff.compare (/home/ubuntu/.nvm/versions/node/v12.16.1/lib/node_modules/pg-diff-cli/node_modules/pg-diff-api/src/index.js:36:27)
    at Run (/home/ubuntu/.nvm/versions/node/v12.16.1/lib/node_modules/pg-diff-cli/main.js:78:39)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.16.1/lib/node_modules/pg-diff-cli/main.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)

**Comment by michaelsogos** [comment]
Hi @JonathonCwik ,

Thanks for the issue.
I was using a long time deprecated nodejs stdout methods.

It has been fixed in v2.0.4
At the moment i don't have a unix machine with me to test it, can i ask you to test it for me?

**Comment by JonathonCwik** [comment]
@michaelsogos This is fixed 👍

**Comment by michaelsogos** [comment]
Great!
