### ISSUE TITLE
Errors are printed to stdout instead of stderr

### ISSUE THREAD

**Issue by codemonstur** [michaelsogos/pg-diff#36]
Running this:

    pg-diff -c generate migration > /dev/null

results in no output. Even though there is no file there.

    $ pg-diff -c generate migration
                                  _   _    __    __                  _   _
      _ __     __ _            __| | (_)  / _|  / _|           ___  | | (_)
     | '_ \   / _` |  _____   / _` | | | | |_  | |_   _____   / __| | | | |
     | |_) | | (_| | |_____| | (_| | | | |  _| |  _| |_____| | (__  | | | |
     | .__/   \__, |          \__,_| |_| |_|   |_|            \___| |_| |_|
     |_|      |___/

         Author: Michael Sogos <michael.sogos@gurustudioweb.it> (https://github.com/michaelsogos)
        Version: 2.1.0
     PostgreSQL: 9.6+
        License: MIT
    Description: PostgreSQL schema and data comparing tool

    Error: Cannot find module '/project-dir/pg-diff-config.json'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
        at Function.Module._load (internal/modules/cjs/loader.js:562:25)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at Function.LoadConfig (/usr/local/lib/node_modules/pg-diff-cli/src/ConfigHandler.js:11:20)
        at Run (/usr/local/lib/node_modules/pg-diff-cli/main.js:68:32)
        at Object.<anonymous> (/usr/local/lib/node_modules/pg-diff-cli/main.js:15:1)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
    Please create the configuration file "pg-diff-config.json" in the same folder where you run pg-diff!

**Comment by michaelsogos** [comment]
Dear @codemonstur 

Got it!

**Comment by michaelsogos** [comment]
Dear @codemonstur 

Release 2.2.0, read docs please.

Can you test it?

**Comment by michaelsogos** [comment]
Dear @codemonstur 

Does it works now for your environment on STERR?
